# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [3]:
print(np.__version__)
print(np.show_config())

2.0.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vpsna6t4/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vpsna6t4/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vpsna6t4/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vpsna6t4/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE6

#### 3. Create a null vector of size 10

In [6]:
null_arr = np.zeros(10)

#### 4. How to find the memory size of any array 

In [7]:
np.size(null_arr)

10

#### 5. How to get the documentation of the numpy add function from the command line?

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [12]:
# null_vec = np.zeros(10)
# null_vec[4]=1
# null_vec

null_vec = (np.arange(10) == 4).astype(int)
null_vec

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49

In [14]:
v = np.arange(10, 49)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last)

In [17]:
# v = np.arange(10, 20)
# v = v[::-1]
# v

v = np.arange(10, 20)
np.flip(v)

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
m = np.arange(0,9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
m = np.arange(4)
m

array([0, 1, 2, 3])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [21]:
a = [1,2,0,0,4,0]
print(np.nonzero(a))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [22]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [24]:
a = np.random.random((3, 3, 3))
print(a) 


[[[0.45881784 0.90986142 0.91962896]
  [0.38803221 0.17016537 0.18920513]
  [0.30151107 0.18532938 0.84413589]]

 [[0.10606869 0.8087928  0.29967795]
  [0.71315235 0.46780223 0.87063307]
  [0.87951042 0.07956799 0.63687955]]

 [[0.82152171 0.98658188 0.69291643]
  [0.29388381 0.49905905 0.6193601 ]
  [0.12235897 0.43630714 0.32105746]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
a = np.random.random((10,10))
print(a.min(),a.max()) 


0.002555576700594253 0.9978572563959544


#### 14. Create a random vector of size 30 and find the mean value

In [28]:
a = np.random.random(10)
print(a.mean())

0.5604710115694269


#### 15. Create a 2d array with 1 on the border and 0 inside

In [32]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0 # exclude  first and last rows (1:-1 refers to rows 1 - 9)

#-------------------------

x2 = np.zeros((10, 10))
x2[0, :] = 1  # Top row
x2[-1, :] = 1  # Bottom row
x2[:, 0] = 1  # Left column
x2[:, -1] = 1  # Right column
    

print(x2)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [38]:
x= np.arange(0,9).reshape(3,3)
new_shape = (x.shape[0] + 2, x.shape[1] + 2)
new_x = np.zeros(new_shape)
new_x[1:-1, 1:-1] = x # except 1st and last row/col

print(new_x)


[[0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [55]:
'''
False, any arithmetic operation involving np.nan results in np.nan
False, Comparing np.nan with itself using the equality operator == always returns False because np.nan represents undefined or missing values and is not equal to any value, including itself.
False, Comparing +ve infinity (np.inf) with np.nan returns False because any comparison involving np.nan is undefined and returns False.
np.nan
True, because np.nan is a member of the set
False, float-point precision issues, 3 * 0.1 is not exactly 0.3

'''

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [41]:
m = np.zeros((5, 5))
np.fill_diagonal(m[1:], [1, 2, 3, 4])
print(m)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [53]:
x = np.zeros((8, 8))
x[::2, ::2] = 1 # even rows
x[1::2, 1::2] = 1  #odd rows
print(x) 





[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [56]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [58]:
m = np.tile(np.array([[0,1],[1,0]]), (4,4)) # No. of repetitions of arr along each axis. 
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [59]:
# normalize formula: (x -mean)/std
m = np.random.random((5,5))
m = (m - np.mean (m)) / (np.std (m))
print(m)

[[-0.48372858 -0.03575611  0.6479512   1.3393201   1.74158035]
 [ 0.49007386 -1.29637233 -1.19955825 -0.52956535  0.73533077]
 [ 0.64010804  0.56880531  1.95286488 -0.21817058 -1.28169662]
 [-1.0920728  -0.37135016 -0.8344474  -1.25608607 -1.01008719]
 [ 0.86617047 -1.11450166  0.25933599 -0.07068985  1.552542  ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [60]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [76]:
m = np.random.random((5, 3))
n = np.random.random((3, 2))

result = np.zeros([5,2])

for i in range(m.shape[0]):    # iterate over rows of m
    for j in range(n.shape[1]):  # iterate over columns of n
        for k in range(m.shape[1]):  # iterate over columns of m or rows of n
            result[i][j] += m[i][k] * n[k][j]


for r in result:
    print(r)

#--------------------------------------
dot_res = np.dot(m, n)
print("dot:\n",dot_res)



[0.27297772 1.08069944]
[0.38695405 1.27722676]
[0.46399804 1.27812317]
[0.38653852 0.9470152 ]
[0.48887419 1.09648286]
dot
 [[0.27297772 1.08069944]
 [0.38695405 1.27722676]
 [0.46399804 1.27812317]
 [0.38653852 0.9470152 ]
 [0.48887419 1.09648286]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [80]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = [-x if 3 <= x <= 8 else x for x in arr]
print(arr)


[1, 2, -3, -4, -5, -6, -7, -8, 9, 10]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [82]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


'''
The Python built-in sum function adds the start value to the sum of the iterable.
The NumPy sum function treats the second argument as an axis specification,
not an initial value to add to the sum.

'''

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [88]:
Z = np.array([1, 2, 3, 4, 5])

print("Z**Z:", Z**Z) # [1**1, 2**2, 3**3, 4**4, 5**5]
print("2 << Z >> 2:", 2 << Z >> 2)
print("1j*Z:", 1j*Z)
print("Z/1/1:", Z/1/1)
try:
    print("Z <- Z:", Z <- Z)
except Exception as e:
    print("Z <- Z: Error -", e)

try:
    print("Z<Z>Z:", Z<Z>Z)
except Exception as e:
    print("Z<Z>Z: Error -", e)


'''
left shift operation 2 << Z results in:

2 << 1 = 4 (binary 10 becomes 100)
2 << 2 = 8 (binary 10 becomes 1000)
2 << 3 = 16 (binary 10 becomes 10000)
2 << 4 = 32 (binary 10 becomes 100000)
2 << 5 = 64 (binary 10 becomes 1000000)

After the right shift operation shifted >> 2, we get:

4 >> 2 = 1 (binary 100 becomes 1)
8 >> 2 = 2 (binary 1000 becomes 10)
16 >> 2 = 4 (binary 10000 becomes 100)
32 >> 2 = 8 (binary 100000 becomes 1000)
64 >> 2 = 16 (binary 1000000 becomes 10000)

'''


Z**Z: [   1    4   27  256 3125]
2 << Z >> 2: [ 1  2  4  8 16]
1j*Z: [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
Z/1/1: [1. 2. 3. 4. 5.]
Z <- Z: [False False False False False]
Z<Z>Z: Error - The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


'\nleft shift operation 2 << Z results in:\n\n2 << 1 = 4 (binary 10 becomes 100)\n2 << 2 = 8 (binary 10 becomes 1000)\n2 << 3 = 16 (binary 10 becomes 10000)\n2 << 4 = 32 (binary 10 becomes 100000)\n2 << 5 = 64 (binary 10 becomes 1000000)\n\nAfter the right shift operation shifted >> 2, we get:\n\n4 >> 2 = 1 (binary 100 becomes 1)\n8 >> 2 = 2 (binary 1000 becomes 10)\n16 >> 2 = 4 (binary 10000 becomes 100)\n32 >> 2 = 8 (binary 100000 becomes 1000)\n64 >> 2 = 16 (binary 1000000 becomes 10000)\n\n'

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [89]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\DELL\AppData\Local\Temp\ipykernel_3476\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\DELL\AppData\Local\Temp\ipykernel_3476\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\DELL\AppData\Local\Temp\ipykernel_3476\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ?

In [90]:
# what does the question mean? :(

[ 1.  2. -6.  4. 10.  6.  6.  7. -8. -9.]
[ 1.  2. -6.  4. 10.  6.  6.  7. -8. -9.]


#### 30. How to find common values between two arrays?

In [91]:
a = np.array([2, 4, 7, 1, 4]) 
b = np.array([7, 2, 9, 0, 5]) 
c = np.intersect1d(a, b) 
print("Common values", c) 


Common values [2 7]


#### 31. How to ignore all numpy warnings (not recommended)?

In [93]:
import warnings

warnings.filterwarnings('ignore')
warnings.resetwarnings()



np.seterr(all='ignore')
print(np.array(0) / np.array(0))
np.seterr(all='warn')



nan


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [94]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

# np.sqrt(-1) returns nan and np.emath.sqrt(-1) returns 1j(complex num)
# == will result in False

False


C:\Users\DELL\AppData\Local\Temp\ipykernel_3476\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow?

In [95]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)

today = np.datetime64('today', 'D')
print("Today: ", today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow) 


Yestraday:  2024-07-04
Today:  2024-07-05
Tomorrow:  2024-07-06


#### 34. How to get all the dates corresponding to the month of July 2016?

In [96]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [100]:
A = np.ones(3)*1
B = np.ones(3)*2
A += B    
A *= -0.5   
print(A)

[-1.5 -1.5 -1.5]


array([2., 2., 2.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

#### 38. Consider a generator function that generates 10 integers and use it to build an array

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

#### 40. Create a random vector of size 10 and sort it

#### 41. How to sum a small array faster than np.sum?

#### 42. Consider two random array A and B, check if they are equal

#### 43. Make an array immutable (read-only) 

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

#### 45. Create random vector of size 10 and replace the maximum value by 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type

#### 49. How to print all the values of an array? 

#### 50. How to find the closest value (to a given scalar) in a vector?

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays?

#### 56. Generate a generic 2D Gaussian-like array

#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### 63. Create an array class that has a name attribute

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).